#!/bin/sh /etc/rc.common
. /lib/functions.sh
START=50

run_agentx1() {
    local lan
    local wan
    local connMode
    local getIP
    local staticIP
    local mask
    local gateway
    local dns
    local user

    config_get lan $1 lan
    config_get wan $1 wan

    config_get connMode $1 connMode

    config_get getIP $1 getIP

    config_get staticIP $1 staticIP
    config_get mask $1 mask

    config_get gateway $1 gateway
    config_get dns $1 dns

    config_get user $1 user

    echo "START..."

    if [ "${getIP}" != "NONE" ];
    then
        if [ [ ${gateway} ] && [ ${dns} ] ];
        then
             agentx1 -L ${lan} -W ${wan} -p ${connMode} -a ${getIP} -u ${user} 
        else
             agentx1 -L ${lan} -W ${wan} -p ${connMode} -a ${getIP} -g ${gateway} -d ${dns} -u ${user} 
        fi 
    else
         agentx1 -L ${lan} -W ${wan} -p ${connMode} -a ${getIP} -i ${staticIP} -n ${mask} -g ${gateway} -d ${dns} -u ${user} 
    fi

    echo "CONNECTED"
}

start() {
    config_load agentx1_config
    config_foreach run_agentx1 conn
}

stop() {
    killall agentx1
    
    echo "agentx1 has stopped"
}
